source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'sinatra-cors', '~> 1.0'
gem 'json', '~> 2.6'
gem 'fileutils', '~> 1.6'
gem 'securerandom', '~> 0.2'

group :development do
  gem 'puma', '~> 6.0'
  gem 'rack', '~> 2.2'
  gem 'rack-protection', '~> 3.0'
end