### Intentionally left blank; mypy config is in mypy.ini

[tool.ruff]
line-length = 140
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[tool.ruff.exclude]
extend = [
    "node_modules",
    "venv",
    "audio-mastering-service/**",
    "main_*",
    "fabfile.py",
]