### Intentionally left blank; mypy config is in mypy.ini

[tool.ruff]
line-length = 100
target-version = "py312"
select = ["E", "F"]
exclude = [
    "node_modules",
    "venv",
    "audio-mastering-service/venv*",
    "audio-mastering-service/services/ml_mastering_backup.py",
]