
# Alembic revision script generated by mako.

"""
Revision ID: 03f4c0434277
Revises: 1a50dc2a1406
Create Date: 2025-10-01 15:25:31.766309
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '03f4c0434277'
down_revision = '1a50dc2a1406'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
