version: '3.8'

services:
  audio-mastering:
    build: .
    ports:
      - "8000:8000"
    environment:
      - STORAGE_TYPE=local
      - LOCAL_STORAGE_PATH=/tmp/mastered_audio
      - BASE_URL=http://localhost:8000
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./temp_audio:/tmp/mastered_audio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for queue system
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  # Optional: MinIO for S3-compatible storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  minio_data:


