name: Test Deploy

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "SSH connection test successful"
            echo "Current time: $(date)"
            echo "Current directory: $(pwd)"
            echo "Docker containers:"
            docker ps --format "table {{.Names}}\t{{.Status}}"

